export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const END_AJAX_CALL = 'END_AJAX_CALL';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

export const USER_INFO_SUCCESS = 'USER_INFO_SUCCESS';
export const USER_INFO_FAIL = 'USER_INFO_FAIL';
export const ERROR_MESSAGE = 'ERROR_MESSAGE';

// Authentication
export const AUTH_RECEIVED_USERINFO = 'AUTH_RECEIVED_USERINFO';
export const AUTH_USERINFO_ERROR = 'AUTH_USERINFO_ERROR';
export const AUTH_RECEIVED_LOGINSUCCESS = 'AUTH_RECEIVED_LOGINSUCCESS';
export const AUTH_RECEIVED_LOGINERROR = 'AUTH_RECEIVED_LOGINERROR';
export const AUTH_RECEIVED_LOGOUT = 'AUTH_RECEIVED_LOGOUT';

// Users
export const USERS_RECEIVED_LIST = 'USERS_RECEIVED_LIST';
export const USERS_RECEIVED_LISTERROR = 'USERS_RECEIVED_LISTERROR';

// Roles
export const USERS_RECEIVED_ROLES = 'USERS_RECEIVED_ROLES';
export const USERS_RECEIVED_ROLES_ERROR = 'USERS_RECEIVED_ROLES_ERROR';

// Values Lists
export const VALUESLISTS_RECEIVED = 'VALUESLISTS_RECEIVED';
export const VALUESLISTS_RECEIVED_ERROR = 'VALUESLISTS_RECEIVED_ERROR';
