export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const END_AJAX_CALL = 'END_AJAX_CALL';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

export const USER_INFO_SUCCESS = 'USER_INFO_SUCCESS';
export const USER_INFO_FAIL = 'USER_INFO_FAIL';
export const ERROR_MESSAGE = 'ERROR_MESSAGE';

// Authentication
export const AUTH_RECEIVED_USERINFO = 'AUTH_RECEIVED_USERINFO';
export const AUTH_USERINFO_ERROR = 'AUTH_USERINFO_ERROR';
export const AUTH_RECEIVED_LOGINSUCCESS = 'AUTH_RECEIVED_LOGINSUCCESS';
export const AUTH_RECEIVED_LOGINERROR = 'AUTH_RECEIVED_LOGINERROR';
export const AUTH_RECEIVED_LOGOUT = 'AUTH_RECEIVED_LOGOUT';