export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const END_AJAX_CALL = 'END_AJAX_CALL';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

export const USER_INFO_SUCCESS = 'USER_INFO_SUCCESS';
export const USER_INFO_FAIL = 'USER_INFO_FAIL';
export const ERROR_MESSAGE = 'ERROR_MESSAGE';

// Authentication
export const AUTH_RECEIVED_USERINFO = 'AUTH_RECEIVED_USERINFO';
export const AUTH_USERINFO_ERROR = 'AUTH_USERINFO_ERROR';
export const AUTH_RECEIVED_LOGINSUCCESS = 'AUTH_RECEIVED_LOGINSUCCESS';
export const AUTH_RECEIVED_LOGINERROR = 'AUTH_RECEIVED_LOGINERROR';
export const AUTH_RECEIVED_LOGOUT = 'AUTH_RECEIVED_LOGOUT';

// Home Page and Widgets
export const HPAGE_RECEIVED_BANNERS = 'HPAGE_RECEIVED_BANNERS';
export const HPAGE_RECEIVED_SBLOCKS = 'HPAGE_RECEIVED_SBLOCKS';
export const HPAGE_RECEIVED_JSHARE = 'HPAGE_RECEIVED_JSHARE';
export const HPAGE_RECEIVED_SERVICES = 'HPAGE_RECEIVED_SERVICES';
export const HPAGE_RECEIVED_EVENTS = 'HPAGE_RECEIVED_EVENTS';
export const HPAGE_RECEIVED_TESTIMONIALS = 'HPAGE_RECEIVED_TESTIMONIALS';
export const HPAGE_ERROR_MESSAGE = 'HPAGE_ERROR_MESSAGE';

// Just Share
export const JSHARE_RECEIVED_GRID_DATA = 'JSHARE_RECEIVED_GRID_DATA';
export const JUSTSHARE_GRID_LOADING = 'JUSTSHARE_GRID_LOADING';
export const JUSTSHARE_GRID_DONELOADING = 'JUSTSHARE_GRID_DONELOADING';
export const JSHARE_RECEIVED_DETAILS = 'JSHARE_RECEIVED_DEATAILS';
export const JSHARE_ERROR_MESSAGE = 'JSHARE_ERROR_MESSAGE';
export const JUSTSHARE_NEWID_SUCCESS = 'JUSTSHARE_NEWID_SUCCESS';
export const JUSTSHARE_NEWID_ERROR = 'JUSTSHARE_NEWID_ERROR';
export const JUSTSHARE_ADDMESSAGE_SUCCESS = 'JUSTSHARE_ADDMESSAGE_SUCCESS';
export const JUSTSHARE_ADDMESSAGE_ERROR = 'JUSTSHARE_ADDMESSAGE_ERROR';
export const JUSTSHARE_USERJUSTSHARE_SUCCESS = 'JUSTSHARE_USERJUSTSHARE_SUCCESS';
export const JUSTSHARE_USERJUSTSHARE_FAIL = 'JUSTSHARE_USERJUSTSHARE_FAIL';
export const JUSTSHARE_FINISH_SUCCESS = 'JUSTSHARE_FINISH_SUCCESS';
export const JUSTSHARE_FINISH_FAIL = 'JUSTSHARE_FINISH_FAIL';
export const JUSTSHARE_SELECTED_GRIDTYPE = 'JUSTSHARE_SELECTED_GRIDTYPE';

// Events
export const EVENTS_RECEIVED_EVENT = 'EVENTS_RECEIVED_EVENT';
export const EVENTS_RECEIVED_ERROR = 'EVENTS_RECEIVED_ERROR';

// Services
export const SERVICES_RECEIVED_SERVICEGROUPS = 'SERVICES_RECEIVED_SERVICEGROUPS';
export const SERVICES_RECEIVED_SERVICEGROUP = 'SERVICES_RECEIVED_SERVICEGROUP';
export const SERVICES_RECEIVED_SERVICES = 'SERVICES_RECEIVED_SERVICES';
export const SERVICES_RECEIVED_SERVICE = 'SERVICES_RECEIVED_SERVICE';
export const SERVICES_RECEIVED_ERROR = 'SERVICES_RECEIVED_ERROR';

// User Admin 
export const USRADM_SIGNUP_SUCCESS = 'USRADM_SIGNUP_SUCCESS';
export const USRADM_SIGNUP_ERROR = 'USRADM_SIGNUP_ERROR';
export const USRADM_USERDETAILS_SUCCESS = 'USRADM_USERDETAILS_SUCCESS';
export const USRADM_USERDETAILS_FAIL = 'USRADM_USERDETAILS_FAIL';
export const USRADM_USERDETAILSFORM_SUCCESS = 'USRADM_USERDETAILSFORM_SUCCESS';
export const USRADM_USERDETAILSFORM_FAIL = 'USRADM_USERDETAILSFORM_FAIL';
export const USRADM_USERDETAILVALUESLISTS_SUCCESS = 'USRADM_USERDETAILVALUESLISTS_SUCCESS';
export const USRADM_USERDETAILVALUESLISTS_ERROR = 'USRADM_USERDETAILVALUESLISTS_ERROR';
export const USRADM_USERDETAILSFORMSUBMIT_SUCCESS = 'USRADM_USERDETAILSFORMSUBMIT_SUCCESS';
export const USRADM_USERDETAILSFORMSUBMIT_FAIL = 'USRADM_USERDETAILSFORMSUBMIT_FAIL';
export const USRADM_FORGOTPASSWORD_SUCCESS = "USRADM_FORGOTPASSWORD_SUCCESS";
export const USRADM_FORGOTPASSWORD_FAIL = "USRADM_FORGOTPASSWORD_FAIL";
export const USRADM_RESETPASSWORD_SUCCESS = "USRADM_RESETPASSWORD_SUCCESS";
export const USRADM_RESETPASSWORD_FAIL = "USRADM_RESETPASSWORD_FAIL";
export const USRADM_REGISTER_SUCCESS = "USRADM_REGISTER_SUCCESS";
export const USRADM_REGISTER_FAIL = "USRADM_REGISTER_FAIL";
export const USRADM_ACCOUNTCONFIRM_SUCCESS = "USRADM_ACCOUNTCONFIRM_SUCCESS";
export const USRADM_ACCOUNTCONFIRM_FAIL = "USRADM_ACCOUNTCONFIRM_FAIL";
export const USRADM_USERAVATARSUBMIT_SUCCESS = "USRADM_USERAVATARSUBMIT_SUCCESS";
export const USRADM_USERAVATARSUBMIT_FAIL = "USRADM_USERAVATARSUBMIT_FAIL";

// Form
export const RECEIVED_VALUELISTS_SUCCESS = 'RECEIVED_VALUELISTS_SUCCESS';
export const RECEIVED_VALUELISTS_ERROR = 'RECEIVED_VALUELISTS_ERROR';
export const FORM_SIGNUP_SUBMITTING = 'FORM_SIGNUP_SUBMITTING';
export const FORM_SIGNUP_SUCCESS = 'FORM_SIGNUP_SUCCESS';
export const FORM_SIGNUP_FAIL = 'FORM_SIGNUP_FAIL';
export const FORM_LOGINFORM_SUBMITTING = 'FORM_LOGINFORM_SUBMITTING';
export const FORM_LOGINFORM_DONESUBMITTING = 'FORM_LOGINFORM_DONESUBMITTING';
export const FORM_LOGINFORM_CLEANERROR = 'FORM_LOGINFORM_CLEANERROR';
export const FORM_PASSWDCHANGE_SUBMITTING = 'FORM_PASSWDCHANGE_SUBMITTING';
export const FORM_PASSWDCHANGE_SUCCESS = 'FORM_PASSWDCHANGE_SUCCESS';
export const FORM_PASSWDCHANGE_FAIL = 'FORM_PASSWDCHANGE_FAIL';
export const FORM_JUSTSHAREFORM_SUBMITTING = 'FORM_JUSTSHAREFORM_SUBMITTING';
export const JUSTSHARE_FORMSUBMIT_SUCCESS = 'JUSTSHARE_FORMSUBMIT_SUCCESS';
export const JUSTSHARE_FORMSUBMIT_ERROR = 'JUSTSHARE_FORMSUBMIT_ERROR';
export const JUSTSHARE_MSGFORMSUBMIT_SUCCESS = 'JUSTSHARE_MSGFORMSUBMIT_SUCCESS';
export const JUSTSHARE_MSGFORMSUBMIT_ERROR = 'JUSTSHARE_MSGFORMSUBMIT_ERROR';

// MODAL
export const MODAL_LOGIN_SHOW = 'MODAL_LOGIN_SHOW';
export const MODAL_LOGIN_HIDE = 'MODAL_LOGIN_HIDE';
