CREATE TABLE [dbo].[Newcomer] (
    [ID]                  INT             IDENTITY (1, 1) NOT NULL,
    [DateCreated]         DATETIME        NOT NULL,
    [HomePhoneNumber]     BIGINT          NULL,
    [OtherPhoneNumber]    BIGINT          NULL,
    [Gender]              INT             NULL,
    [ConsentToContact]    BIT             CONSTRAINT [ColumnDefault_dac492a1-a258-4588-99da-59a590d030f7] DEFAULT ((1)) NULL,
    [LengthOfTimeInCAD]   INT             NULL,
    [CountryOfOrigin]     NVARCHAR (50)   NULL,
    [ImmigrantCategory]   INT             NULL,
    [LanguagesSpoken]     NVARCHAR (100)  NULL,
    [Status]              CHAR (1)        NOT NULL,
    [LastModified]        DATETIME        NOT NULL,
    [MinistryID]          INT             NULL,
    [AgeRangeID]          INT             NULL,
    [PostalCode]          CHAR (7)        NULL,
    [NearestIntersection] NVARCHAR (256)  NULL,
    [LevelOfEnglish]      INT             NULL,
    [UserID]              INT             NOT NULL,
    [MaritalStatus]       BIT             NULL,
    [Education]           INT             NULL,
    [OtherTraining]       NVARCHAR (2000) NULL,
    CONSTRAINT [PrimaryKey_fdaaa270-a648-4ede-bd73-bcc1d0d7d8f1] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_Newcomer_0] FOREIGN KEY ([Gender]) REFERENCES [dbo].[Choices_Gender] ([ID]),
    CONSTRAINT [FK_Newcomer_1] FOREIGN KEY ([LengthOfTimeInCAD]) REFERENCES [dbo].[Choices_LengthOfTimeInCAD] ([ID]),
    CONSTRAINT [FK_Newcomer_2] FOREIGN KEY ([ImmigrantCategory]) REFERENCES [dbo].[Choices_ImmigrantCategory] ([ID]),
    CONSTRAINT [FK_Newcomer_3] FOREIGN KEY ([MinistryID]) REFERENCES [dbo].[Choices_Ministry] ([ID])
);

