CREATE PROCEDURE [dbo].[sp_Events_Update]
@cId nvarchar(128),
@cName NVARCHAR(50)=NULL, 
@cDescription NVARCHAR(1000)=NULL, 
@dStartDate datetime, 
@dEndDate datetime, 
@bPublished bit=0, 
@dStartPublishDate datetime,
@dEndPublishDate datetime, 
@bFinished bit=0, 
@nMaxSlots int=0, 
@nCurSlots int=0, 
@cImage NVARCHAR(255)=NULL, 
@cCreatedBy nvarchar(128), 
@nType int=0,
@cStatus nchar(1)='O',
@dAlterDate datetime,
@cExternalLink nvarchar(256) = '',
@cTitle nvarchar(50)='',
@cSubTitle nvarchar(100)='',
@cHeadImg nvarchar(256)= '',
@cText1 ntext = '',
@cText2 ntext = '',
@cFooter ntext = '',
@cLocation ntext = ''

AS

UPDATE [dbo].[Events] 
SET [Name] = @cName, 
[Description] = @cDescription, 
[StartDate] = @dStartDate, 
[EndDate] = @dEndDate, 
[Published] = @bPublished, 
[StartPublishDate] = @dStartPublishDate, 
[EndPublishDate] = @dEndPublishDate, 
[Finished] = @bFinished, 
[MaxSlots] = @nMaxSlots, 
[CurSlots] = @nCurSlots, 
[Image] = @cImage, 
[CreatedBy] = @cCreatedBy, 
[Type] = @nType,
[AlterDate] = @dAlterDate,
[ExternalLink] = @cExternalLink,
[Status] = @cStatus,
[HeadImg] = @cHeadImg,
[Title] = @cTitle,
[SubTitle] = @cSubTitle,
[Text1] = @cText1,
[Text2] = @cText2,
[Footer] = @cFooter,
[Location] = @cLocation
WHERE [Id] = @cId